name: Rosetta Validation

on: [push]

env:
  go_version: 1.16
  GO111MODULE: on

jobs:
  rosetta-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3

    - name: Start a private ethereum network
      uses: ./.github/actions/geth
      id: geth

    - name: Sleep for 20 seconds
      run: sleep 20s
      shell: bash

    - name: Get latest block from geth node
      run: |
        curl -X POST "http://127.0.0.1:8546" --header 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", true],"id":1}'
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install web3

    - name: deploy erc20 USDC
      run: .github/scripts/init_erc20.sh
      shell: bash

    - name: Get erc20 infos
      run: python .github/scripts/contract_infos.py
      shell: bash

    - name: Populate transactions
      run: python .github/scripts/populate_txns.py
      shell: bash

    - name: Start Rosetta Server
      run: .github/scripts/setup.sh
      shell: bash

    - name: Run Check:construction test
      run: .github/scripts/construction.sh
      shell: bash

    - name: Run Check:data test
      run: .github/scripts/cli.sh
      shell: bash