name: tests

on: [push]

env:
  go_version: 1.19
  GO111MODULE: on

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version }}
      - run: .github/scripts/cli.sh && make test
