name: validate config files

on: [push]

env:
  go_version: 1.19
  GO111MODULE: on

jobs:
  goerli-configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version }}
      - name: validate optimism goerli configs
        run: .github/scripts/validate-goerli-config.sh
        shell: bash
  mainnet-configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version }}
      - name: validate optimism mainnet configs
        run: echo "TODO"
